In [9]:
import pandas as pd
df1 = pd.DataFrame({ 'a': ['a0', 'a1', 'a2', 'a3'],
                    'b': ['b0', 'b1', 'b2', 'b3'],
                    'c': ['c0', 'c1', 'c2', 'c3']},
                    index=[0, 1, 2, 3])
df1

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

In [10]:
df2 = pd.DataFrame({ 'a': ['a2', 'a3', 'a4', 'a5'],
                    'b': ['b2', 'b3', 'b4', 'b5'],
                    'c': ['c2', 'c3', 'c4', 'c5'],
                    'd': ['d2', 'd3', 'd4', 'd5']},
                    index=[0, 1, 2, 3])
df2

    a   b   c   d
0  a2  b2  c2  d2
1  a3  b3  c3  d3
2  a4  b4  c4  d4
3  a5  b5  c5  d5

In [11]:
result1 = pd.concat([df1, df2])
result1

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
0  a2  b2  c2   d2
1  a3  b3  c3   d3
2  a4  b4  c4   d4
3  a5  b5  c5   d5

In [12]:
result2 = pd.concat([df1, df2], ignore_index=True)
result2

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
4  a2  b2  c2   d2
5  a3  b3  c3   d3
6  a4  b4  c4   d4
7  a5  b5  c5   d5

In [13]:
result3_in = pd.concat([df1, df2], axis=0, join='inner')
result3_in

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3
0  a2  b2  c2
1  a3  b3  c3
2  a4  b4  c4
3  a5  b5  c5

In [16]:
sr1 = pd.Series(['e0', 'e1', 'e2', 'e3'], name='e')
sr2 = pd.Series(['f0', 'f1', 'f2'], name='f', index=[3, 4, 5])
sr3 = pd.Series(['g0', 'g1', 'g2', 'g3'], name='g')
sr4 = pd.Series(['a6', 'b6', 'c6', 'd6'], index=['a', 'b', 'c', 'd'])

result4 = pd.concat([df1, sr1], axis=1)
result4

    a   b   c   e
0  a0  b0  c0  e0
1  a1  b1  c1  e1
2  a2  b2  c2  e2
3  a3  b3  c3  e3

In [17]:
result5 = pd.concat([df2, sr2], axis=1)
result5

     a    b    c    d    f
0   a2   b2   c2   d2  NaN
1   a3   b3   c3   d3  NaN
2   a4   b4   c4   d4  NaN
3   a5   b5   c5   d5   f0
4  NaN  NaN  NaN  NaN   f1
5  NaN  NaN  NaN  NaN   f2

In [18]:
result6 = pd.concat([df2, sr4.to_frame() .T], ignore_index=True)
result6

    a   b   c   d
0  a2  b2  c2  d2
1  a3  b3  c3  d3
2  a4  b4  c4  d4
3  a5  b5  c5  d5
4  a6  b6  c6  d6

In [19]:
result7 = pd.concat([sr1, sr3], axis=1)
result7

    e   g
0  e0  g0
1  e1  g1
2  e2  g2
3  e3  g3

In [20]:
result8 = pd.concat([sr1, sr3], axis=0)
result8

0    e0
1    e1
2    e2
3    e3
0    g0
1    g1
2    g2
3    g3
dtype: object

In [22]:
import pandas as pd
df1 = pd.read_excel('../data/stock_price.xlsx')
df1

       id stock_name          value   price
0  128940       한미약품   59385.666667  421000
1  130960     CJ E&M   58540.666667   98900
2  138250      엔에스쇼핑   14558.666667   13200
3  139480        이마트  239230.833333  254500
4  142280     녹십자엠에스     468.833333   10200
5  145990        삼양사   82750.000000   82000
6  185750        종근당   40293.666667  100500
7  192400      쿠쿠홀딩스  179204.666667  177500
8  199800         툴젠   -2514.333333  115400
9  204210     모두투어리츠    3093.333333    3475

In [25]:
df2 = pd.read_excel('../data/stock_valuation.xlsx')
df2

       id       name           eps     bps        per       pbr
0  130960     CJ E&M   6301.333333   54068  15.695091  1.829178
1  136480         하림    274.166667    3551  11.489362  0.887074
2  138040    메리츠금융지주   2122.333333   14894   6.313806  0.899691
3  139480        이마트  18268.166667  295780  13.931338  0.860437
4  145990        삼양사   5741.000000  108090  14.283226  0.758627
5  161390      한국타이어   5648.500000   51341   7.453306  0.820007
6  181710  NHN엔터테인먼트   2110.166667   78434  30.755864  0.827447
7  185750        종근당   3990.333333   40684  25.185866  2.470259
8  204210     모두투어리츠     85.166667    5335  40.802348  0.651359
9  207940   삼성바이오로직스   4644.166667   60099  89.790059  6.938551

In [26]:
merge_inner = pd.merge(df1, df2, how='inner', on='id')
merge_inner

,id,stock_name,value,price,name,eps,bps,per,pbr
0,130960,CJ E&M,58540.666667,98900,CJ E&M,6301.333333,54068,15.695091,1.829178
1,139480,이마트,239230.833333,254500,이마트,18268.166667,295780,13.931338,0.860437
2,145990,삼양사,82750.000000,82000,삼양사,5741.000000,108090,14.283226,0.758627
3,185750,종근당,40293.666667,100500,종근당,3990.333333,40684,25.185866,2.470259
4,204210,모두투어리츠,3093.333333,3475,모두투어리츠,85.166667,5335,40.802348,0.651359

In [27]:
merge_outer = pd.merge(df1, df2, how='outer', on='id')
merge_outer

,id,stock_name,value,price,name,eps,bps,per,pbr
0,128940,한미약품,59385.666667,421000.0,NaN,NaN,NaN,NaN,NaN
1,130960,CJ E&M,58540.666667,98900.0,CJ E&M,6301.333333,54068.0,15.695091,1.829178
2,136480,NaN,NaN,NaN,하림,274.166667,3551.0,11.489362,0.887074
3,138040,NaN,NaN,NaN,메리츠금융지주,2122.333333,14894.0,6.313806,0.899691
4,138250,엔에스쇼핑,14558.666667,13200.0,NaN,NaN,NaN,NaN,NaN
5,139480,이마트,239230.833333,254500.0,이마트,18268.166667,295780.0,13.931338,0.860437
6,142280,녹십자엠에스,468.833333,10200.0,NaN,NaN,NaN,NaN,NaN
7,145990,삼양사,82750.000000,82000.0,삼양사,5741.000000,108090.0,14.283226,0.758627
8,161390,NaN,NaN,NaN,한국타이어,5648.500000,51341.0,7.453306,0.820007
9,181710,NaN,NaN,NaN,NHN엔터테인먼트,2110.166667,78434.0,30.755864,0.827447
10,185750,종근당,40293.666667,100500.0,종근당,3990.333333,40684.0,25.185866,2.470259
11,192400,쿠쿠홀딩스,179204.666667,177500.0,NaN,NaN,NaN,NaN,NaN
12,199800,툴젠,-2514.333333,115400.0,NaN,NaN,NaN,NaN,NaN
13,204210,모두투어리츠,3093.333333,3475.0,모두투어리츠,85.166667,5335.0,40.802348,0.651359
14,207940,NaN,NaN,NaN,삼성바이오로직스,4644.166667,60099.0,89.790059,6.938551

In [28]:
merge_left = pd.merge(df1, df2, how='left',
                      left_on=['id', 'stock_name'], right_on=['id', 'name'])
merge_left

,id,stock_name,value,price,name,eps,bps,per,pbr
0,128940,한미약품,59385.666667,421000,NaN,NaN,NaN,NaN,NaN
1,130960,CJ E&M,58540.666667,98900,CJ E&M,6301.333333,54068.0,15.695091,1.829178
2,138250,엔에스쇼핑,14558.666667,13200,NaN,NaN,NaN,NaN,NaN
3,139480,이마트,239230.833333,254500,이마트,18268.166667,295780.0,13.931338,0.860437
4,142280,녹십자엠에스,468.833333,10200,NaN,NaN,NaN,NaN,NaN
5,145990,삼양사,82750.000000,82000,삼양사,5741.000000,108090.0,14.283226,0.758627
6,185750,종근당,40293.666667,100500,종근당,3990.333333,40684.0,25.185866,2.470259
7,192400,쿠쿠홀딩스,179204.666667,177500,NaN,NaN,NaN,NaN,NaN
8,199800,툴젠,-2514.333333,115400,NaN,NaN,NaN,NaN,NaN
9,204210,모두투어리츠,3093.333333,3475,모두투어리츠,85.166667,5335.0,40.802348,0.651359

In [29]:
merge_right = pd.merge(df1, df2, how='right', left_on=['id', 'stock_name'], right_on=['id', 'name'])
merge_right

,id,stock_name,value,price,name,eps,bps,per,pbr
0,130960,CJ E&M,58540.666667,98900.0,CJ E&M,6301.333333,54068,15.695091,1.829178
1,136480,NaN,NaN,NaN,하림,274.166667,3551,11.489362,0.887074
2,138040,NaN,NaN,NaN,메리츠금융지주,2122.333333,14894,6.313806,0.899691
3,139480,이마트,239230.833333,254500.0,이마트,18268.166667,295780,13.931338,0.860437
4,145990,삼양사,82750.000000,82000.0,삼양사,5741.000000,108090,14.283226,0.758627
5,161390,NaN,NaN,NaN,한국타이어,5648.500000,51341,7.453306,0.820007
6,181710,NaN,NaN,NaN,NHN엔터테인먼트,2110.166667,78434,30.755864,0.827447
7,185750,종근당,40293.666667,100500.0,종근당,3990.333333,40684,25.185866,2.470259
8,204210,모두투어리츠,3093.333333,3475.0,모두투어리츠,85.166667,5335,40.802348,0.651359
9,207940,NaN,NaN,NaN,삼성바이오로직스,4644.166667,60099,89.790059,6.938551

In [30]:
merge_cross = pd.merge(df1, df2, how='cross')
merge_cross

,id_x,stock_name,value,price,id_y,name,eps,bps,per,pbr
0,128940,한미약품,59385.666667,421000,130960,CJ E&M,6301.333333,54068,15.695091,1.829178
1,128940,한미약품,59385.666667,421000,136480,하림,274.166667,3551,11.489362,0.887074
2,128940,한미약품,59385.666667,421000,138040,메리츠금융지주,2122.333333,14894,6.313806,0.899691
3,128940,한미약품,59385.666667,421000,139480,이마트,18268.166667,295780,13.931338,0.860437
4,128940,한미약품,59385.666667,421000,145990,삼양사,5741.000000,108090,14.283226,0.758627
...,...,...,...,...,...,...,...,...,...,...
95,204210,모두투어리츠,3093.333333,3475,161390,한국타이어,5648.500000,51341,7.453306,0.820007
96,204210,모두투어리츠,3093.333333,3475,181710,NHN엔터테인먼트,2110.166667,78434,30.755864,0.827447
97,204210,모두투어리츠,3093.333333,3475,185750,종근당,3990.333333,40684,25.185866,2.470259
98,204210,모두투어리츠,3093.333333,3475,204210,모두투어리츠,85.166667,5335,40.802348,0.651359
99,204210,모두투어리츠,3093.333333,3475,207940,삼성바이오로직스,4644.166667,60099,89.790059,6.938551

In [31]:
price = df1[df1['price'] < 50000]
price

       id stock_name         value  price
2  138250      엔에스쇼핑  14558.666667  13200
4  142280     녹십자엠에스    468.833333  10200
9  204210     모두투어리츠   3093.333333   3475

In [32]:
value  = pd.merge(price, df2)
value

,id,stock_name,value,price,name,eps,bps,per,pbr
0,204210,모두투어리츠,3093.333333,3475,모두투어리츠,85.166667,5335,40.802348,0.651359

In [33]:
sdf1 = pd.DataFrame({'employee': ['Alice', 'Sam', 'Eva'],
                     'department': ['HR', 'Tech', 'HR']})
sdf2 = pd.DataFrame({'employee': ['Eva', 'Alice', 'Sam'],
                     'start_year': [2018, 2019, 2020]})
result_one_to_one = pd.merge(sdf1,sdf2, on='employee')
result_one_to_one

  employee department  start_year
0    Alice         HR        2019
1      Sam       Tech        2020
2      Eva         HR        2018

In [35]:
sdf3 = pd.DataFrame({'department':['HR', 'Tech'],
                     'manager': ['Tina', 'Alex']})
result_many_to_one = pd.merge(sdf1, sdf3, on='department')
result_many_to_one

  employee department manager
0    Alice         HR    Tina
1      Sam       Tech    Alex
2      Eva         HR    Tina

In [37]:
# 라이브러리 불러오기
import requests
import pandas as pd

# 예제 2.7의 get_financials() 함수를 사용 (Dapada apiKey 필요)

my_key = "----발급받은 API 키를 입력-----"

# 특정 종목(stockCode)의 재무항목(indicatorName) 데이터를 가져오는 함수를 정의
def get_financials(stockCode, indicatorName, apiKey, consolidated=True, ttm=True):
    
    if consolidated:   # 연결 기준
        if ttm:        # Trailing 12 Months (12개월 누적)
            url = f"https://api.dapada.io/company/getConsolidatedFinancialDataByTTM?apiKey={apiKey}&indicatorName={indicatorName}&stockCode={stockCode}"            
        else:          # 해당 분기 기준 (3개월 집계)
            url = f"https://api.dapada.io/company/getConsolidatedFinancialDataByCUR?apiKey={apiKey}&indicatorName={indicatorName}&stockCode={stockCode}"       
            
    else:              # 별도 기준
        if ttm:        # Trailing 12 Months (12개월 누적)
            url = f"https://api.dapada.io/company/getSeparatedFinancialDataByTTM?apiKey={apiKey}&indicatorName={indicatorName}&stockCode={stockCode}"            
        else:          # 해당 분기 기준 (3개월 집계)
            url = f"https://api.dapada.io/company/getSeparatedFinancialDataByCUR?apiKey={apiKey}&indicatorName={indicatorName}&stockCode={stockCode}"       
           
    headers = {"apiKey": f"{apiKey}"}
    response = requests.get(url, headers=headers)
    result = response.json()
    return pd.DataFrame(result)

# 삼성전자(005930)의 연결 재무제표 (분기 기준)에서 '매출액' 항목의 데이터 수집
df_revenue = get_financials(stockCode='005930', 
                            indicatorName='매출액', 
                            apiKey=my_key, 
                            consolidated=True, 
                            ttm=False)


# 열 이름 변경
df_revenue.columns = ['매출액', '분기']

# 분기 열을 인덱스로 설정
df_revenue = df_revenue.set_index('분기', drop=True)

# 2022년 데이터만 선택
df_revenue = df_revenue[df_revenue.index.str.startswith('2022')]

df_revenue

UnicodeEncodeError: 'latin-1' codec can't encode characters in position 4-7: ordinal not in range(256)

In [38]:
# 삼성전자(005930)의 연결 재무제표 (분기 기준)에서 '영업이익' 항목의 데이터 수집
df_margin = get_financials(stockCode='005930', 
                           indicatorName='영업이익', 
                           apiKey=my_key, 
                           consolidated=True, 
                           ttm=False)

# 열 이름 변경
df_margin.columns = ['영업이익', '분기']

# 분기 열을 인덱스로 설정
df_margin = df_margin.set_index('분기', drop=True)

# 3분기 데이터만 선택
df_margin = df_margin[df_margin.index.str.endswith('Q3')]

df_margin

UnicodeEncodeError: 'latin-1' codec can't encode characters in position 4-7: ordinal not in range(256)

In [39]:
# 데이터프레임 결합(join)
df_revenue_margin = df_revenue.join(df_margin)
df_revenue_margin

NameError: name 'df_revenue' is not defined

In [40]:
# 데이터프레임 결합(join) - 교집합
df_revenue_margin2 = df_revenue.join(df_margin, how='inner')
df_revenue_margin2

NameError: name 'df_revenue' is not defined