In [12]:
# CSV 파일로 저장하기
# DataFrame객체.to_csv('파일 이름(경로)')

import pandas as pd

data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }
df = pd.DataFrame(data)
df = df.set_index('name')
df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [13]:
df.to_csv("../data/df_sample.csv")

In [14]:
df.to_csv('../data/df_sample_no_index.csv', index=False)

In [15]:
# json 파일로 저장하기
import pandas as pd

data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }
df = pd.DataFrame(data)
df = df.set_index('name')
df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [16]:
# DataFrame객체.to_json('파일 이름(경로)')

df.to_json('../data/df_sample.json')

In [17]:
df.to_json('../data/df_sample_split.json', orient='split')

In [18]:
df.to_json('../data/df_sample_records.json', orient='records')

In [19]:
df.to_json('../data/df_sample_index.json', orient='index')

In [21]:
df.to_json('../data/df_sample_columns.json', orient='columns')

In [22]:
df.to_json('../data/df_sample_values.json', orient='values')