In [32]:
import pandas as pd

In [33]:
fruit_names = pd.Series([
    'Apple', 'Banana', 'Cherry'
])

fruit_names

0     Apple
1    Banana
2    Cherry
dtype: str

In [34]:
pd.Series([
    'Apple', 'Banana', 'Cherry'
], dtype='string')

0     Apple
1    Banana
2    Cherry
dtype: string

In [35]:
pd.Series([
    'Apple', 'Banana', 'Cherry'
], dtype=pd.SrtingDtype())

AttributeError: module 'pandas' has no attribute 'SrtingDtype'

In [ ]:
fruit_names.astype('string')

0     Apple
1    Banana
2    Cherry
dtype: string

In [ ]:
# 문자열 메서드
import pandas as pd
import numpy as np

ser = pd.Series([
    'Apple_사과', "Banana_바나나", "Cherry_체리", np.nan
], index=['First ', ' Second', " Third", 'Fourth'])
ser

ser2 = pd.Series([
    'Apple_사과', "Banana_바나나", "Cherry_체리", np.nan
], index=['First ', ' Second', " Third", 'Fourth'], dtype = 'string')
ser2

First        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth           <NA>
dtype: string

In [ ]:
print(ser.str.lower())
print(ser.str.upper())
print(ser.str.len())

First        apple_사과
 Second    banana_바나나
 Third      cherry_체리
Fourth            NaN
dtype: str
First        APPLE_사과
 Second    BANANA_바나나
 Third      CHERRY_체리
Fourth            NaN
dtype: str
First       8.0
 Second    10.0
 Third      9.0
Fourth      NaN
dtype: float64

In [ ]:
result1 = ser.str.split('_')
result1

First        [Apple, 사과]
 Second    [Banana, 바나나]
 Third      [Cherry, 체리]
Fourth               NaN
dtype: object

In [ ]:
result2 = ser.str.split('_', expand=True)
result2

              0    1
First     Apple   사과
 Second  Banana  바나나
 Third   Cherry   체리
Fourth      NaN  NaN

In [ ]:
ser.str.split('_').str.get(1)

First       사과
 Second    바나나
 Third      체리
Fourth     NaN
dtype: object

In [ ]:
# 문자열 메서드

idx = ser.index
print(idx.str.strip())

Index(['First', 'Second', 'Third', 'Fourth'], dtype='str')

In [ ]:
print(ser.str.replace('_', ':', regex=False))

First        Apple:사과
 Second    Banana:바나나
 Third      Cherry:체리
Fourth            NaN
dtype: str

In [36]:
ser.str.replace('[^a-zA-Z\s]', '', regex=True)

<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\use\AppData\Local\Temp\ipykernel_15908\3776728894.py:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  ser.str.replace('[^a-zA-Z\s]', '', regex=True)

First       Apple
 Second    Banana
 Third     Cherry
Fourth        NaN
dtype: str

In [37]:
ser.str[0]

First        A
 Second      B
 Third       C
Fourth     NaN
dtype: str

In [38]:
ser.str[0:4]

First      Appl
 Second    Bana
 Third     Cher
Fourth      NaN
dtype: str

In [40]:
ser.str.contains('A')

First       True
 Second    False
 Third     False
Fourth     False
dtype: bool

In [45]:
ser.str.contains(r'[A|B][a-z]*')

First       True
 Second     True
 Third     False
Fourth     False
dtype: bool

In [47]:
ser.str.fullmatch(r'[A|B][a-z]+')

First      False
 Second    False
 Third     False
Fourth     False
dtype: bool

In [48]:
ser3 = pd.Series([
    'a1', 'b2', 'c3', 'd4a5', 'e6e7', 'f8'
], dtype='string')
ser3

0      a1
1      b2
2      c3
3    d4a5
4    e6e7
5      f8
dtype: string

In [50]:
ser3.str.extractall(r'(\d)').groupby(level=0).agg(''.join)

    0
0   1
1   2
2   3
3  45
4  67
5   8

In [53]:
ser3.str.extractall(r'([a-z])').groupby(level=0).agg(''.join)

    0
0   a
1   b
2   c
3  da
4  ee
5   f

In [ ]:
# 숫자형 필드랑 컬럼으로 분리
split_columns = ser3.str.extract(r'(?P<Letter>)[a-z]+)(?P<Digit>\d+)')

PatternError: unbalanced parenthesis at position 18